### ISSUE TITLE
Demo Day (D-Day)

### ISSUE THREAD

**Issue by MohamedKasem99** [Top-iaas/topiaas#7]
We need to have the following for the demo day in 2 weeks from now (see the date of this issue). 

- [x]  User registration system
- [x]  User profile 
- [x]  Kubernetes cluster
- [x] Demo data upload
- [x] Demo billing
- [x] Demo orange app inside website
- [ ] Demo jupyter notebook 
- [x] Demo a full user flow from signup to billing

points to emphasize:
- Topiaas is a plug and play infrastructure
- Orangeml models and widgets are extendable 
- How easy it is to switch between clouds and applications (app and cloud agnostic)

**Comment by mmahrouss** [comment]
Some notes we talked abt
Using this infra as a system for plug and play ML

We would great generic components that define i/o data that be further expanded later on

**Comment by MohamedKasem99** [comment]
Postponing the jupyter notebook containers for later
